language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
notifications:
  slack:
    secure: TpACQhV7aJ0+SP3No/Vb2xKU669gY8e4dHImZYLgKeLnG7YSdHpgFYGzDPm/nzwkTl9TD2m4v9NYz2vnxItiWzK8HBv9DY7bbx4xloo1xqk/5YS2YERqiizMoYjZthK5QwKEqBo9XHH7yFiB7GWJjaW4q3U7Tj94x1tZ3QGjlFmRp0CEwChLNwk03g0OiAmj2mLx7Y2JjFQpMy6/WJOIkRVs3N2wRwsyBaQxU43OTtEKHR3YY2W4JpcmjebZY+ZoJ1tHo/VPE0/tTJDYzj3jGwwxnE/CJrEiuiXxgDDm2YARmYMpbfeKcg+uq4N5wXV7lQ2PJwsCvucgobRNrdyhnwdtWg6uD4hDLXfsipL+KFqF85FpHCRYZdeNHuecbT0pDEcYN3QSB3UouJmK1ODJ/nlW9JPTV7yGc+HRAGGrq1Y+CdTCXlmvuQTzBaXhBjIyNzLuG64Q8COTNXuDqeNdRdzaOcSCA8rikUzHq8qDNO7RDJC4OmC40w83xkeSeGvdpu8OdG+6L1GNGS0LIL16t5iuZo9QCvh3W2r8iNvx6FjvrBc1zDroKpBmuMcvzmvNMC1PtLQyOVzIYJx62qvPBLtan+DFcQ8uoFeEZO35mviiBAt/N/gyPvChlryr3aMlFaCIE/oiNKwXAH/bNd+zn+UvWcK+t1Hgs1W+ilOd2yk=
